# Generated by Django 2.2.6 on 2020-05-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='videofile',
            field=models.FileField(null=True, upload_to='media/home', verbose_name=''),
        ),
    ]
