# Generated by Django 3.0.6 on 2020-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200528_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='videofile',
            field=models.FileField(null=True, upload_to='video/home', verbose_name=''),
        ),
    ]
