# Generated by Django 3.0.6 on 2020-06-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200601_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.FileField(blank=True, default='', upload_to='images/<django.db.models.fields.CharField>', verbose_name='')),
            ],
        ),
    ]
