# Generated by Django 3.0.6 on 2020-06-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='directory',
            field=models.CharField(default='home', max_length=255),
        ),
    ]
