# Generated by Django 3.0.6 on 2020-06-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200604_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='directory',
            field=models.CharField(default='home', max_length=50),
        ),
    ]
