# Generated by Django 3.0.6 on 2020-05-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('price2', models.FloatField(default='0.0')),
                ('stock', models.IntegerField()),
                ('unit', models.CharField(default='brls', max_length=10)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
