# Generated by Django 2.2.7 on 2020-05-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
