# Generated by Django 2.2.7 on 2020-05-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200528_0248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
