# Generated by Django 3.0.6 on 2020-05-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('price2', models.FloatField(default='0.0')),
                ('stock', models.IntegerField()),
                ('unit', models.CharField(default='brls', max_length=100)),
                ('youtube_id', models.CharField(default='', max_length=100)),
                ('button_name', models.CharField(default='procedure', max_length=100)),
                ('image_url', models.CharField(max_length=2083)),
                ('photo', models.ImageField(null=True, upload_to='images/products')),
            ],
        ),
        migrations.DeleteModel(
            name='Fuel',
        ),
    ]
