# Generated by Django 3.0.6 on 2020-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200530_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
