# Generated by Django 3.0.6 on 2020-06-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
        ('products', '0009_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='procedures.Procedure', verbose_name='Procedure'),
        ),
    ]
