# Generated by Django 3.0.6 on 2020-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200603_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code2',
            field=models.CharField(default='', max_length=10),
        ),
    ]
