# Generated by Django 3.0.6 on 2020-06-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_code2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
