# Generated by Django 3.0.6 on 2020-06-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
        ('products', '0013_delete_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procedures.Procedure', verbose_name='Procedure'),
        ),
    ]
