# Generated by Django 3.0.6 on 2020-06-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
