# Generated by Django 3.0.6 on 2020-06-08 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200608_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 2, 52, 10, 427173, tzinfo=utc)),
        ),
    ]
