# Generated by Django 3.0.6 on 2020-06-08 07:35

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200608_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(default='', max_length=255)),
                ('directory', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(blank=True, default='', upload_to=products.models.UploadedConfigPath)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='Product')),
            ],
        ),
    ]
