# Generated by Django 3.0.6 on 2020-06-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, default='', upload_to='images/products'),
        ),
    ]
