# Generated by Django 3.0.6 on 2020-06-08 07:53

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200608_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='photo',
            field=models.FileField(blank=True, default='', upload_to=products.models.UploadedConfigPath),
        ),
    ]
