# Generated by Django 3.0.6 on 2020-06-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200608_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='productid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
