# Generated by Django 3.0.6 on 2020-06-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_productdetail_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='product',
            name='doc',
            field=models.IntegerField(default=0),
        ),
    ]
