# Generated by Django 3.0.6 on 2020-06-09 14:28

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200609_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', editable=False, upload_to=products.models.UploadedConfigPath),
        ),
    ]
