# Generated by Django 3.0.6 on 2020-06-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productdetail_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='thumbnail',
        ),
    ]
