# Generated by Django 2.2.7 on 2020-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_productdetail_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='thumbnail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='productid',
            field=models.CharField(max_length=50),
        ),
    ]
