# Generated by Django 3.0.6 on 2020-06-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20200611_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='directory',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
