# Generated by Django 3.0.6 on 2020-06-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200611_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtubeID',
            field=models.CharField(default='', max_length=255),
        ),
    ]
